get:
  operationId: getComments
  summary: Get Comments.
  parameters:
    - $ref: "../../parameters/query/postId.yaml"
  responses:
    "200":
      description: An array of Comments.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "../../schemas/Comment.yaml"
    "404":
      $ref: "../../responses/Error.yaml"
    "500":
      $ref: "../../responses/Error.yaml"
    default:
      $ref: "../../responses/Error.yaml"
  tags:
    - comments
post:
  operationId: addComment
  summary: Add a Comment.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../../schemas/Comment.yaml"
  responses:
    "201":
      description: Added a Comment.
      content:
        application/json:
          schema:
            $ref: "../../schemas/Comment.yaml"
    "404":
      $ref: "../../responses/Error.yaml"
    "422":
      $ref: "../../responses/Error.yaml"
    "500":
      $ref: "../../responses/Error.yaml"
    default:
      $ref: "../../responses/Error.yaml"
  tags:
    - comments
