export const NAME_ACTIONS = {
    BLOG:{
        BLOG_HOME_SCREEN:'BLOG_HOME_SCREEN',
        BLOG_HOME_SCREEN_GET_BLOGS_LIST:'BLOG_HOME_SCREEN_GET_BLOGS_LIST',
        BLOG_HOME_SCREEN_GET_BLOGS_LIST_SUCCESS:'BLOG_HOME_SCREEN_GET_BLOGS_LIST_SUCCESS',
        BLOG_HOME_SCREEN_GET_BLOGS_LIST_FAILED:'BLOG_HOME_SCREEN_GET_BLOGS_LIST_FAILED',

        BLOG_CREATE_SCREEN:'BLOG_CREATE_SCREEN',

        BLOG_DETAIL_SCREEN:'BLOG_DETAIL_SCREEN'
    }
}