export const GET_LIST_POST_REQUEST = 'GET_LIST_POST_REQUEST';
export const GET_LIST_POST_SUCCESS = 'GET_LIST_POST_SUCCESS';
export const GET_LIST_POST_FAIL = 'GET_LIST_POST_FAIL';

export const GET_COMMENTS_IN_POST_REQUEST = 'GET_COMMENTS_IN_POST_REQUEST';
export const GET_COMMENTS_IN_POST_SUCCESS = 'GET_COMMENTS_IN_POST_SUCCESS';
export const GET_COMMENTS_IN_POST_FAIL = 'GET_COMMENTS_IN_POST_FAIL';

export const SEARCH_POST_REQUEST = 'SEARCH_POST_REQUEST';
export const SEARCH_POST_SUCCESS = 'SEARCH_POST_SUCCESS';
export const SEARCH_POST_FAIL = 'SEARCH_POST_FAIL';

export const DEFAULT = 'DEFAULT';
