export enum commentPostIdTypes {
  FETCH_COMMENT_POST_ID_REQUEST = "FETCH_COMMENT_POST_ID_REQUEST",
  FETCH_COMMENT_POST_ID_SUCCESS = "FETCH_COMMENT_POST_ID_SUCCESS",
  FETCH_COMMENT_POST_ID_FAILURE = "FETCH_COMMENT_POST_ID_FAILURE",
}
