export enum postTypes {
  FETCH_POST_REQUEST = "FETCH_POST_REQUEST",
  FETCH_POST_SUCCESS = "FETCH_POST_SUCCESS",
  FETCH_POST_FAILURE = "FETCH_POST_FAILURE",
}

export enum postIdTypes {
  FETCH_POST_ID_REQUEST = "FETCH_POST_ID_REQUEST",
  FETCH_POST_ID_SUCCESS = "FETCH_POST_ID_SUCCESS",
  FETCH_POST_ID_FAILURE = "FETCH_POST_ID_FAILURE",
}
