const COMMENTS_FETCH_REQUEST = 'COMMENTS_FETCH_REQUEST';
const COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS';
const COMMENTS_FETCH_FAIL = 'COMMENTS_FETCH_FAIL';

export { COMMENTS_FETCH_REQUEST, COMMENTS_FETCH_SUCCESS, COMMENTS_FETCH_FAIL };
