const COMMENTS_FETCH_REQUEST = 'COMMENTS_FETCH_REQUEST';
const COMMENTS_FETCH_SUCCESS = 'COMMENTS_FETCH_SUCCESS';
const COMMENTS_FETCH_FAIL = 'COMMENTS_FETCH_FAIL';

const COMMENTS_BY_POST_ID_FETCH_REQUEST = 'COMMENTS_BY_POST_ID_FETCH_REQUEST';
const COMMENTS_BY_POST_ID_FETCH_SUCCESS = 'COMMENTS_BY_POST_ID_FETCH_SUCCESS';
const COMMENTS_BY_POST_ID_FETCH_FAIL = 'COMMENTS_BY_POST_ID_FETCH_FAIL';

export {
  COMMENTS_FETCH_REQUEST,
  COMMENTS_FETCH_SUCCESS,
  COMMENTS_FETCH_FAIL,
  COMMENTS_BY_POST_ID_FETCH_REQUEST,
  COMMENTS_BY_POST_ID_FETCH_SUCCESS,
  COMMENTS_BY_POST_ID_FETCH_FAIL,
};
