const POSTS_FETCH_REQUEST = 'POSTS_FETCH_REQUEST';
const POSTS_FETCH_SUCCESS = 'POSTS_FETCH_SUCCESS';
const POSTS_FETCH_FAIL = 'POSTS_FETCH_FAIL';

export { POSTS_FETCH_REQUEST, POSTS_FETCH_SUCCESS, POSTS_FETCH_FAIL };
