const USERS_FETCH_REQUEST = 'GET_USERS';
const USERS_FETCH_SUCCESS = 'SET_USERS';
const USERS_FETCH_FAIL = 'USERS_FETCH_FAIL';

const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
const USER_FETCH_FAIL = 'USER_FETCH_FAIL';

export {
  USERS_FETCH_REQUEST,
  USERS_FETCH_SUCCESS,
  USERS_FETCH_FAIL,
  USER_FETCH_REQUEST,
  USER_FETCH_SUCCESS,
  USER_FETCH_FAIL,
};
