const GET_USERS = 'GET_USERS';
const SET_USERS = 'SET_USERS';

const USER_FETCH_REQUEST = 'USER_FETCH_REQUEST';
const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS';
const USER_FETCH_FAIL = 'USER_FETCH_FAIL';

export {
  GET_USERS,
  SET_USERS,
  USER_FETCH_REQUEST,
  USER_FETCH_SUCCESS,
  USER_FETCH_FAIL,
};
