title: Comment
description: Schema for Comment.
type: object
properties:
  id:
    type: string
    description: The ID of the Comment.
  owner:
    type: string
    description: The owner ID of the Comment.
  post:
    type: string
    description: The post ID of the Comment.
  content:
    type: string
    description: The content of the Comment.
  create_at:
    type: integer
    format: int64
    description: The creating time of the Post (epoch time in milliseconds).
required:
  - owner
  - post
