title: User
description: Schema for User.
type: object
properties:
  id:
    type: string
    description: The ID of the User.
  username:
    type: string
    description: The username of the User.
  name:
    type: string
    description: The name of the User.
  dob:
    type: string
    format: date
    description: The date of birth of the User.
  create_at:
    type: integer
    format: int64
    description: The creating time of the User (epoch time in milliseconds).
required:
  - username
