import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import "bootstrap/dist/css/bootstrap.min.css";
import '@/scss/custom.scss';
import '@/scss/style.scss';

import { ReduxProvider } from '../redux/ReduxProvider';

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
          <body className={montserrat.className}>
            <ReduxProvider>
              {children}
            </ReduxProvider>
          </body>
      </html>
  )
}
