version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_volume/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zigvy

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5001:8080

networks:
  app-tier:
    driver: bridge

volumes:
  postgres:
  pgadmin: