version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_volume/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zigvy

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5001:8080
  
  zigvy-backend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: zigvy-backend
    ports:
      - 4000:4000
    env_file:
      - ./.env
    restart: always

networks:
  app-tier:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  zigvy-backend: