export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_TOTAL_POSTS = "GET_TOTAL_POSTS";
export const GET_TOTAL_POSTS_SUCCESS = "GET_TOTAL_POSTS_SUCCESS";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const UPDATE_LOADING = "UPDATE_LOADING";
export const UPDATE_POST = "UPDATE_POST";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
