export const NAME_EPICS = {
    BLOG_HOME_SCREEN:{
        EPIC_BLOG_HOME_SCREEN_GET_BLOGS_LIST:'EPIC_BLOG_HOME_SCREEN_GET_BLOGS_LIST',
        EPIC_BLOG_HOME_SCREEN_GET_BLOGS_LIST_SUCCESS:'EPIC_BLOG_HOME_SCREEN_GET_BLOGS_LIST_SUCCESS',
        EPIC_BLOG_HOME_SCREEN_GET_BLOGS_LIST_FAILED:'EPIC_BLOG_HOME_SCREEN_GET_BLOGS_LIST_FAILED',
    },
    BLOG_CREATE_SCREEN:{
        
    },
    BLOG_DETAIL_SCREEN:{
        
    }
}