const actionTypes = {
    GET_POSTS: "GET_POSTS",
    GET_POSTS_BY_ID: "GET_POSTS_BY_ID",
    GET_POST_COMMENTS: "GET_POST_COMMENTS",
    GET_USERS: "GET_USERS",
    GET_USER_BY_ID: "GET_USER_BY_ID",
    GET_COMMENTS: "GET_COMMENTS",
    GET_COMMENTS_BY_POST_ID: "GET_COMMENTS_BY_POST_ID"
};

export default actionTypes;