version: '3.8'
services:
    postgres:
      container_name: postgres_container
      image: postgres
      environment:
        POSTGRES_USER: blog
        POSTGRES_PASSWORD: blogAdmin
    
      ports:
        - "5432:5432"
    
      restart: unless-stopped
  