export const GET_LIST_PRODUCTS = "GET_LIST_POST";
export const GET_LIST_PRODUCTS_SUCCESS = "GET_LIST_POST_SUCCESS";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const TEST_GET_LIST_PRODUCT_REQUEST = "TEST_GET_LIST_PRODUCT";
export const TEST_GET_LIST_PRODUCT_SUCCESS = "TEST_GET_LIST_PRODUCT_SUCCESS";
export const TEST_GET_LIST_PRODUCT_FAILURE = "TEST_GET_LIST_PRODUCT_FAILURE";
