export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT_STUDIO = "LOGOUT_STUDIO";

export const LOGIN_STUDIO_REQUEST = "LOGIN_STUDIO_REQUEST";
export const LOGIN_STUDIO_SUCCESS = "LOGIN_STUDIO_SUCCESS";
export const LOGIN_STUDIO_FAILURE = "LOGIN_STUDIO_FAILURE";
