const LOGIN = "LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";
const LOGOUT = "LOGOUT";

const GET_POSTS = "GET_POSTS";
const GET_POSTS_SEARCHED = "GET_POSTS_SEARCHED";
const GET_POSTS_SEARCHED_SUCCESS = "GET_POSTS_SEARCHED_SUCCESS";
const GET_POSTS_SEARCHED_FAILURE = "GET_POSTS_SEARCHED_FAILURE";
const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";
const LOAD_MORE_POSTS = "LOAD_MORE_POSTS";

const GET_POST = "GET_POST";
const GET_POST_SUCCESS = "GET_POSTS_SUCCES";
const GET_POST_FAILURE = "GET_POST_FAILURE";

export {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOAD_MORE_POSTS,
  LOGOUT,
  GET_POSTS,
  GET_POSTS_SEARCHED,
  GET_POSTS_SEARCHED_SUCCESS,
  GET_POSTS_SUCCESS,
  GET_POSTS_FAILURE,
  GET_POST,
  GET_POST_SUCCESS,
  GET_POST_FAILURE,
  GET_POSTS_SEARCHED_FAILURE,
};
