export const ADD_CONTENT_FORM = 'ADD_CONTENT_FORM';

export const FETCH_POST_ALL = 'FETCH_POST_ALL';
export const FETCH_POST_ALL_SUCCESS = 'FETCH_POST_ALL_SUCCESS';

export const FETCH_POST_USER = 'FETCH_POST_USER';
export const FETCH_POST_USER_SUCCESS = 'FETCH_POST_USER_SUCCESS';

export const ADD_POST = 'ADD_POST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';

export const SEARCH_POST = 'SEARCH_POST';

export const PAGINATION_POST_ALL = 'PAGINATION_POST_ALL';

export const COUNT_POST_ALL = 'COUNT_POST_ALL';
export const COUNT_POST_ALL_SUCCESS = 'COUNT_POST_ALL_SUCCESS';