// import styles from "../styles/Home.module.css";
import React from "react";
import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";

import { ACTION_TYPES } from "../redux/actions/postsAction";
import PostCard from "./components/PostCard/PostCard";
import LogoImage from '@/public/logo.png'

export default function Home() {
  const dispatch = useDispatch(); 
  // Using the useSelector Hook to fetch the state from store.
  const fetchedPosts = useSelector((state) => state.posts.postsList);
  console.log(fetchedPosts)

  React.useEffect(() => {
    dispatch({
      type: ACTION_TYPES.FETCH_POSTS,
    });
    console.log(fetchedPosts);
  }, []);

  return (
    <div className="p-4 bg-gray-50">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className="flex flex-row justify-between bg-slate-400">
               {/* <Image src={LogoImage} width={50} height={50} alt="Logo" /> */}
                <p>BLogs</p>
                <p>Mai Thuc Lan</p>
            </div>
        {fetchedPosts?.map((c) => (
          <PostCard key={c.id} id={c.id} body={c.body} />
        ))}

        {/* <Comment /> */} 
      </main>
    </div>
  );
}
