export const NEXT_PAGE = "NEXT_PAGE"
export const PREVIOUS_PAGE = "PREVIOUS_PAGE"
export const PAGINATION_CLICKED = "PAGINATION_CLICKED"

export const LOADING = "LOADING"
export const FINISHED = "FINISHED"

export const POST_FETCH_SUCCEED = "POST_FETCH_SUCCEED"
export const POST_FETCH_REQUESTED = "POST_FETCH_REQUESTED"
