import { Inter } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import { StoreProvider } from "./server-action/store/storePovider";
import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <StoreProvider>
      <>
        <Head>
          <title>My Blog</title>
        </Head>
        <html lang="en">
          <body className={inter.className}>
            {children}
            {/* <BootStrapClient /> */}
          </body>
        </html>
      </>
    </StoreProvider>
  );
}
