# Generated by Django 3.0.2 on 2020-01-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200109_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentblog',
            name='created_at',
            field=models.CharField(default=1576506719083, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postblog',
            name='created_at',
            field=models.CharField(max_length=250),
        ),
    ]
