export const GET_USER_FETCH = "GET_USERS_FETCH";
export const GET_USER_SUCCESS = "GET_USERS_SUCCESS";
export const GET_POST_FETCH = "GET_POSTS_FETCH";
export const GET_POST_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_COMMENT_FETCH = "GET_COMMENTS_FETCH";
export const GET_COMMENT_SUCCESS = "GET_COMMENTS_SUCCESS";
