version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin_developer
      POSTGRES_PASSWORD: admin_developer_password
      POSTGRES_DB: zigvy_interview

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5001:8080

networks:
  app-tier:
    driver: bridge

volumes:
  postgres:
  pgadmin:
