// Export Constants

export const TOGGLE_ADD_POST = 'TOGGLE_ADD_POST';

export const GET_ALL_POSTS_REQUEST = 'GET_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAIL = 'GET_POSTS_FAIL'

export const GET_POST_DETAIL_REQUEST = 'GET_POST_DETAIL_REQUEST';
export const GET_POST_DETAIL_SUCCESS = 'GET_POST_DETAIL_SUCCESS';
export const GET_POST_DETAIL_FAIL = 'GET_POST_DETAIL_FAIL';

export const ADD_NEW_POST_REQUEST = 'ADD_NEW_POST_REQUEST';
export const ADD_NEW_POST_SUCCESS = 'ADD_NEW_POST_SUCCESS';
export const ADD_NEW_POST_FAIL = 'ADD_NEW_POST_FAIL';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAIL = 'GET_USERS_FAIL';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';

export const SEARCH_POST_REQUEST = 'SEARCH_POST_REQUEST';
export const SEARCH_POST_SUCCESS = 'SEARCH_POST_SUCCESS';
export const SEARCH_POST_FAIL = 'SEARCH_POST_FAIL';
