export const NAME_EPICS = {
    EPIC_LOGIN_SCREEN:{
        EPIC_LOGIN_SUCCESS:'EPIC_LOGIN_SUCCESS',
        EPIC_LOGIN_FAILED:'EPIC_LOGIN_FAILED',
        EPIC_LOGIN_SCREEN_RESET_LOGIN_STATUS:'EPIC_LOGIN_SCREEN_RESET_LOGIN_STATUS',
    },
    EPIC_SIGNUP_SCREEN:{
        
    }
}