export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
export const GET_ALL_COMMENTS_SUCCESS = "GET_ALL_COMMENTS_SUCCESS";
export const GET_COMMENT_BY_POST = "GET_COMMENT_BY_ID";
export const GET_COMMENT_BY_POST_SUCCESS = "GET_COMMENT_BY_POST_SUCCESS";
export const GET_ALL_POSTS = "GET_ALL_POST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_POST_BY_ID = "GET_POST_BY_ID";
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS";
export const GET_COMMENT_OF_POST = "GET_COMMENT_OF_POST";
export const GET_COMMENT_OF_POST_SUCCESS = "GET_COMMENT_OF_POST_SUCCESS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

