export const tags: string[] = [
	"programming",
	"web development",
	"machine learning",
	"cybersecurity",
	"mobile development",
	"adventure",
	"culture",
	"solo travel",
	"road trip",
	"hiking",
	"fitness",
	"mental health",
	"nutrition",
	"yoga",
	"self-care",
	"cooking",
	"vegetarian",
	"food photography",
	"street food",
	"desserts",
	"physics",
	"astronomy",
	"biology",
	"neuroscience",
	"space exploration",
];
