export const GET_POST_BY_USERID_SAGA = "GET_POST_BY_USERID_SAGA";
export const GET_POST_BY_USERID = "GET_POST_BY_USERID";

export const GET_COMMENTS_OF_POST_SAGA = "GET_COMMENTS_OF_POST_SAGA";
export const GET_COMMENTS_OF_POST = "GET_COMMENTS_OF_POST";

export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
export const GET_ALL_COMMENTS_SAGA = "GET_ALL_COMMENTS_SAGA";

export const GET_POSTS_SEARCH_ACTION = "GET_POSTS_SEARCH_ACTION";

export const GET_ALL_POSTS_SAGA = "GET_ALL_POSTS_SAGA";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
