//Type Saga
export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_COMMENTS = 'FETCH_COMMENT'
export const FETCH_POST_DETAIL = 'FETCH_POST_DETAIL'

//Type Store
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR'
export const FETCH_POST_DETAIL_SUCCESS = 'FETCH_POST_DETAIL_SUCCESS'
export const FETCH_POST_DETAIL_ERROR = 'FETCH_POST_DETAIL_ERROR'