import React from "react";
import Feather from "react-native-vector-icons/Feather";
import IoniconsIcon from "react-native-vector-icons/Ionicons";
import MaterialIcon from "react-native-vector-icons/MaterialIcons";
import MaterialIcons from "react-native-vector-icons/MaterialIcons";
import Entypo from "react-native-vector-icons/Entypo";
import AntDesign from "react-native-vector-icons/AntDesign";
import SimpleLineIcons from "react-native-vector-icons/SimpleLineIcons";
import FontAwesome from "react-native-vector-icons/FontAwesome";
import FontAwesome5 from "react-native-vector-icons/FontAwesome5";
import Foundation from "react-native-vector-icons/Foundation";
import Ionicons from "react-native-vector-icons/Ionicons";
import EvilIcons from "react-native-vector-icons/EvilIcons";
import Octicons from "react-native-vector-icons/Octicons";
import MaterialCommunityIcons from "react-native-vector-icons/MaterialCommunityIcons";
import Fontisto from "react-native-vector-icons/Fontisto";

export const UserIcon = (props: Object) => <AntDesign name="user" {...props} />;
export const LockIcon = (props: Object) => <AntDesign name="lock" {...props} />;
export const FabBackIcon = (props: Object) => <AntDesign name="left" {...props} />;
export const SearchIcon = (props: Object) => <AntDesign name="search1" {...props} />;
export const OptionIcon = (props: Object) => <SimpleLineIcons name="options-vertical" {...props} />;
export const CommentIcon = (props: Object) => <AntDesign name="wechat" {...props} />;