const actionTypes = Object.freeze({
    FETCH_POSTS_REQUEST: 'FETCH_POSTS_REQUEST',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',

    FETCH_COMMENT_REQUEST: 'FETCH_COMMENT_REQUEST',
    FETCH_COMMENT_SUCCESS: 'FETCH_COMMENT_SUCCESS',
    FETCH_COMMENT_FAILURE: 'FETCH_COMMENT_FAILURE',

})

export default actionTypes;