const CommentActionTypes = {
    FETCH_COMMENTS_START: 'FETCH_COMMENTS_START',
    FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
    FETCH_COMMENTS_FAILURE: 'FETCH_COMMENTS_FAILURE',
};

export default CommentActionTypes;
