export enum postsTypes {
	FETCH_POSTS_REQUEST = "FETCH_POSTS_REQUEST",
	FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS",
	FETCH_POSTS_FAILED = "FETCH_POSTS_FAILED",
	CLEAR_POSTS = "CLEAR_POSTS",
	PERFORM_SEARCH = "PERFORM_SEARCH",
}
