export const COMMENT_FETCH = "COMMENT_FETCH";
export const POST_FETCH = "POST_FETCH";
export const CREATE_NEW_POST_REQUEST = "CREATE_NEW_POST_REQUEST";
export const CREATE_NEW_COMMENT_REQUEST = "CREATE_NEW_COMMENT_REQUEST";
export const POST_FETCH_LOAD_MORE = "POST_FETCH_LOAD_MORE";

export const COMMENT_FETCH_SUCCEED = "COMMENT_FETCH_SUCCEED";
export const COMMENT_FETCH_FAILED = "COMMENT_FETCH_FAILED";

export const CREATE_NEW_POST_SUCCEED = "CREATE_NEW_POST_SUCCEED";
export const CREATE_NEW_POST_FAILED = "CREATE_NEW_POST_FAILED";

export const POST_FETCH_SUCCEED = "POST_FETCH_SUCCEED";
export const POST_FETCH_FAILED = "POST_FETCH_FAILED";

export const POST_FETCH_LOAD_MORE_SUCCEED = "POST_FETCH_LOAD_MORE_SUCCEED";
export const POST_FETCH_LOAD_MORE_FAILED = "POST_FETCH_LOAD_MORE_FAILED";

export const CREATE_NEW_COMMENT_SUCCEED = "CREATE_NEW_COMMENT_SUCCEED";
export const CREATE_NEW_COMMENT_FAILED = "CREATE_NEW_COMMENT_FAILED";


export const POST_LOADING_ON = "POST_LOADING_ON";
export const POST_LOADING_OFF = "POST_LOADING_OFF";
