export const NAME_ACTIONS = {
    LOGIN:{
        LOGIN_SCREEN:'LOGIN_SCREEN',
        LOGIN_SCREEN_LOGIN:'LOGIN_SCREEN_LOGIN',
        LOGIN_SCREEN_LOGIN_SUCCESS:'LOGIN_SCREEN_LOGIN_SUCCESS',
        LOGIN_SCREEN_LOGIN_FAILED:'LOGIN_SCREEN_LOGIN_FAILED',
        LOGIN_SCREEN_RESET_LOGIN_STATUS:'LOGIN_SCREEN_RESET_LOGIN_STATUS',

        SIGNUP_SCREEN:'SIGNUP_SCREEN',
        SIGNUP_SCREEN_SIGNUP:'SIGNUP_SCREEN_SIGNUP',
        SIGNUP_SCREEN_SIGNUP_SUCCESS:'SIGNUP_SCREEN_SIGNUP_SUCCESS',
        SIGNUP_SCREEN_SIGNUP_FAILED:'SIGNUP_SCREEN_SIGNUP_FAILED'
    }
}