version: "3"
services:
  mongodb:
    container_name: ${MONGO_HOST}
    image: mongo:7.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - zigvy-mongodb:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - zigvy-network
  app:
    container_name: zigvy-app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    networks:
      - zigvy-network
    depends_on:
      mongodb:
        condition: service_healthy
networks:
  zigvy-network:
volumes:
  zigvy-mongodb:
